// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWS.DAL;

#nullable disable

namespace TWS.DAL.Migrations
{
    [DbContext(typeof(TWSContext))]
    [Migration("20230127174725_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWS.DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39b3f4a4-a369-421d-b70e-fc06c8eb13bf"),
                            Abrv = "manufacturer-1",
                            Name = "Manufacturer 1"
                        },
                        new
                        {
                            Id = new Guid("2a19d24a-06eb-4fd4-99b1-71a75c2d9e4c"),
                            Abrv = "manufacturer-2",
                            Name = "Manufacturer 2"
                        },
                        new
                        {
                            Id = new Guid("38de2d38-ade5-4c8d-9553-ab79425a5bbe"),
                            Abrv = "manufacturer-3",
                            Name = "Manufacturer 3"
                        },
                        new
                        {
                            Id = new Guid("f0a48dc7-4193-4d1f-a6cf-9787f34608c8"),
                            Abrv = "manufacturer-4",
                            Name = "Manufacturer 4"
                        },
                        new
                        {
                            Id = new Guid("2e1e830f-0222-41cf-887f-493e9c312cb5"),
                            Abrv = "manufacturer-5",
                            Name = "Manufacturer 5"
                        },
                        new
                        {
                            Id = new Guid("deb94709-ac3b-4541-bdf8-9d21d8bd431c"),
                            Abrv = "manufacturer-6",
                            Name = "Manufacturer 6"
                        },
                        new
                        {
                            Id = new Guid("9e68ca38-7dab-46b8-97c7-4be0c8126271"),
                            Abrv = "manufacturer-7",
                            Name = "Manufacturer 7"
                        },
                        new
                        {
                            Id = new Guid("ee8d0735-bf8a-4290-a775-fd1303e4faf1"),
                            Abrv = "manufacturer-8",
                            Name = "Manufacturer 8"
                        },
                        new
                        {
                            Id = new Guid("852ccb8e-14b7-47a6-841e-a9e04a7a6d86"),
                            Abrv = "manufacturer-9",
                            Name = "Manufacturer 9"
                        },
                        new
                        {
                            Id = new Guid("da917078-cf7f-4368-a4ae-652173b1eaa1"),
                            Abrv = "manufacturer-10",
                            Name = "Manufacturer 10"
                        },
                        new
                        {
                            Id = new Guid("b09f0934-3299-4c78-84ac-18d1142e496d"),
                            Abrv = "manufacturer-11",
                            Name = "Manufacturer 11"
                        },
                        new
                        {
                            Id = new Guid("9655770b-50b9-4807-ac06-82663c03fa52"),
                            Abrv = "manufacturer-12",
                            Name = "Manufacturer 12"
                        },
                        new
                        {
                            Id = new Guid("fe78fd13-930d-467f-bc95-679bbddd56d7"),
                            Abrv = "manufacturer-13",
                            Name = "Manufacturer 13"
                        },
                        new
                        {
                            Id = new Guid("0084fa4e-4ec2-407c-8d26-50eb790a5a04"),
                            Abrv = "manufacturer-14",
                            Name = "Manufacturer 14"
                        },
                        new
                        {
                            Id = new Guid("9665dc0a-f531-4cb0-a478-605dedce69d9"),
                            Abrv = "manufacturer-15",
                            Name = "Manufacturer 15"
                        },
                        new
                        {
                            Id = new Guid("891c214b-c488-4132-ae1e-b8d1ee0dc162"),
                            Abrv = "manufacturer-16",
                            Name = "Manufacturer 16"
                        },
                        new
                        {
                            Id = new Guid("142faf68-613b-4131-aad6-275a302d9152"),
                            Abrv = "manufacturer-17",
                            Name = "Manufacturer 17"
                        },
                        new
                        {
                            Id = new Guid("5532cfa0-ee51-47d6-9d2b-386a4f137772"),
                            Abrv = "manufacturer-18",
                            Name = "Manufacturer 18"
                        },
                        new
                        {
                            Id = new Guid("e31acad6-2948-49ee-9f18-d8eb46c1fa3a"),
                            Abrv = "manufacturer-19",
                            Name = "Manufacturer 19"
                        },
                        new
                        {
                            Id = new Guid("8e3e01ae-f5f4-4476-a1ee-0c31a582cd70"),
                            Abrv = "manufacturer-20",
                            Name = "Manufacturer 20"
                        });
                });

            modelBuilder.Entity("TWS.DAL.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dda3e0b9-996c-4d0c-acc0-863e47351b11"),
                            Abrv = "product-1",
                            Description = "",
                            ManufacturerId = new Guid("39b3f4a4-a369-421d-b70e-fc06c8eb13bf"),
                            Name = "Product1",
                            Price = 100m,
                            SKU = "p1"
                        },
                        new
                        {
                            Id = new Guid("a1007999-a699-41f1-97b6-1b910b227f0b"),
                            Abrv = "product-2",
                            Description = "",
                            ManufacturerId = new Guid("0084fa4e-4ec2-407c-8d26-50eb790a5a04"),
                            Name = "Product2",
                            Price = 200m,
                            SKU = "p2"
                        },
                        new
                        {
                            Id = new Guid("3f6a98fb-742d-4148-86b5-de363fef3f50"),
                            Abrv = "product-3",
                            Description = "",
                            ManufacturerId = new Guid("39b3f4a4-a369-421d-b70e-fc06c8eb13bf"),
                            Name = "Product3",
                            Price = 300m,
                            SKU = "p3"
                        },
                        new
                        {
                            Id = new Guid("6fb115b0-234d-4f62-941e-305714d17dde"),
                            Abrv = "product-4",
                            Description = "",
                            ManufacturerId = new Guid("38de2d38-ade5-4c8d-9553-ab79425a5bbe"),
                            Name = "Product4",
                            Price = 400m,
                            SKU = "p4"
                        },
                        new
                        {
                            Id = new Guid("84ac3658-c2bb-4072-b8a8-3da60c47403b"),
                            Abrv = "product-5",
                            Description = "",
                            ManufacturerId = new Guid("2e1e830f-0222-41cf-887f-493e9c312cb5"),
                            Name = "Product5",
                            Price = 500m,
                            SKU = "p5"
                        },
                        new
                        {
                            Id = new Guid("7ebd4cfb-2a36-4256-8e61-c9c65f9dd05e"),
                            Abrv = "product-6",
                            Description = "",
                            ManufacturerId = new Guid("5532cfa0-ee51-47d6-9d2b-386a4f137772"),
                            Name = "Product6",
                            Price = 600m,
                            SKU = "p6"
                        },
                        new
                        {
                            Id = new Guid("b0cd82b6-5c9f-41b7-8c30-cb5f7666e4b3"),
                            Abrv = "product-7",
                            Description = "",
                            ManufacturerId = new Guid("da917078-cf7f-4368-a4ae-652173b1eaa1"),
                            Name = "Product7",
                            Price = 700m,
                            SKU = "p7"
                        },
                        new
                        {
                            Id = new Guid("7b8e4fec-f25a-46ce-8431-6b47cb36e380"),
                            Abrv = "product-8",
                            Description = "",
                            ManufacturerId = new Guid("2a19d24a-06eb-4fd4-99b1-71a75c2d9e4c"),
                            Name = "Product8",
                            Price = 800m,
                            SKU = "p8"
                        },
                        new
                        {
                            Id = new Guid("ed6b2486-3717-44c6-8cbf-940a7c9c9c36"),
                            Abrv = "product-9",
                            Description = "",
                            ManufacturerId = new Guid("f0a48dc7-4193-4d1f-a6cf-9787f34608c8"),
                            Name = "Product9",
                            Price = 900m,
                            SKU = "p9"
                        },
                        new
                        {
                            Id = new Guid("fbe07c5d-e574-46d6-8368-f4e291e83891"),
                            Abrv = "product-10",
                            Description = "",
                            ManufacturerId = new Guid("39b3f4a4-a369-421d-b70e-fc06c8eb13bf"),
                            Name = "Product10",
                            Price = 1000m,
                            SKU = "p10"
                        },
                        new
                        {
                            Id = new Guid("a5d394e9-41e9-43f0-8f49-1678a1006f00"),
                            Abrv = "product-11",
                            Description = "",
                            ManufacturerId = new Guid("b09f0934-3299-4c78-84ac-18d1142e496d"),
                            Name = "Product11",
                            Price = 100m,
                            SKU = "p11"
                        },
                        new
                        {
                            Id = new Guid("efc52ac9-82d3-497d-a093-23934b00ddae"),
                            Abrv = "product-12",
                            Description = "",
                            ManufacturerId = new Guid("deb94709-ac3b-4541-bdf8-9d21d8bd431c"),
                            Name = "Product12",
                            Price = 200m,
                            SKU = "p12"
                        },
                        new
                        {
                            Id = new Guid("9f833cc7-6e56-45af-9c8e-47850c5e5864"),
                            Abrv = "product-13",
                            Description = "",
                            ManufacturerId = new Guid("deb94709-ac3b-4541-bdf8-9d21d8bd431c"),
                            Name = "Product13",
                            Price = 300m,
                            SKU = "p13"
                        },
                        new
                        {
                            Id = new Guid("3c146f41-55d1-4e86-9cb6-1f2d39659eea"),
                            Abrv = "product-14",
                            Description = "",
                            ManufacturerId = new Guid("9665dc0a-f531-4cb0-a478-605dedce69d9"),
                            Name = "Product14",
                            Price = 400m,
                            SKU = "p14"
                        },
                        new
                        {
                            Id = new Guid("b275fe7e-8bbb-4a93-9608-54c7183654c5"),
                            Abrv = "product-15",
                            Description = "",
                            ManufacturerId = new Guid("38de2d38-ade5-4c8d-9553-ab79425a5bbe"),
                            Name = "Product15",
                            Price = 500m,
                            SKU = "p15"
                        },
                        new
                        {
                            Id = new Guid("4cb70937-5af1-4792-9b4b-68f1b311c28c"),
                            Abrv = "product-16",
                            Description = "",
                            ManufacturerId = new Guid("2a19d24a-06eb-4fd4-99b1-71a75c2d9e4c"),
                            Name = "Product16",
                            Price = 600m,
                            SKU = "p16"
                        },
                        new
                        {
                            Id = new Guid("9c82497b-05bc-48a4-9b81-06a23a6fa4a0"),
                            Abrv = "product-17",
                            Description = "",
                            ManufacturerId = new Guid("852ccb8e-14b7-47a6-841e-a9e04a7a6d86"),
                            Name = "Product17",
                            Price = 700m,
                            SKU = "p17"
                        },
                        new
                        {
                            Id = new Guid("1c08edba-5a5d-4b69-9ab5-8e2a5856efac"),
                            Abrv = "product-18",
                            Description = "",
                            ManufacturerId = new Guid("8e3e01ae-f5f4-4476-a1ee-0c31a582cd70"),
                            Name = "Product18",
                            Price = 800m,
                            SKU = "p18"
                        },
                        new
                        {
                            Id = new Guid("24f5b17c-28df-4ab6-853c-edd035f0e63b"),
                            Abrv = "product-19",
                            Description = "",
                            ManufacturerId = new Guid("2a19d24a-06eb-4fd4-99b1-71a75c2d9e4c"),
                            Name = "Product19",
                            Price = 900m,
                            SKU = "p19"
                        },
                        new
                        {
                            Id = new Guid("2d93729b-31fe-4f23-94a3-da2f2a9a0bdb"),
                            Abrv = "product-20",
                            Description = "",
                            ManufacturerId = new Guid("2a19d24a-06eb-4fd4-99b1-71a75c2d9e4c"),
                            Name = "Product20",
                            Price = 1000m,
                            SKU = "p20"
                        });
                });

            modelBuilder.Entity("TWS.DAL.Entities.ProductEntity", b =>
                {
                    b.HasOne("TWS.DAL.Entities.ManufacturerEntity", null)
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWS.DAL.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
